services:
  - type: web
    name: gaincoon
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
